# Generated by Django 4.0.2 on 2022-02-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
